export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_USER_LOADING = "CREATE_USER_LOADING";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const LOAD_USER_LOADING = "LOAD_USER_LOADING";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAIL = "PROFILE_FAIL";

export const CHANGE_PASSWORD_LOADING = "CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_LOADING = "FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const LOGOUT_SUCCESS = " LOGOUT_SUCCESS";

export const CREATE_MESSAGES_LOADING = "CREATE_MESSAGES_LOADING";
export const CREATE_MESSAGES_SUCCESS = "CREATE_MESSAGE_SUCCESS";

export const CLEAR_MESSAGES_LOADING = "CLEAR_MESSAGES_LOADING";
export const CLEAR_MESSAGES_SUCCESS = "CLEAR_MESSAGES_SUCCESS";

export const CLEAR_ERRORS_LOADING = "CLEAR_ERRORS_LOADING";
export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";

export const GET_ERRORS = "GET_ERRORS";

export const CHECK_USER_TYPE_LOADING = "CHECK_USER_TYPE_LOADING";
export const CHECK_USER_TYPE_SUCCESS = "CHECK_USER_TYPE_SUCCESS";
export const CHECK_USER_TYPE_FAIL = "CHECK_USER_TYPE_FAIL";

export const REST_PASSWORD_LOADING = "REST_PASSWORD_LOADING";
export const REST_PASSWORD_SUCCESS = "REST_PASSWORD_SUCCESS";
export const REST_PASSWORD_FAIL = "REST_PASSWORD_FAIL";

export const CODE_VERIFICATION_LOADING = "CODE_VERIFICATION_LOADING ";
export const CODE_VERIFICATION_SUCCESS = "CODE_VERIFICATION_SUCCESS";
export const CODE_VERIFICATION_FAIL = "CODE_VERIFICATION_FAIL";

export const TASK_CREATE_LOADING = "TASK_CREATE_LOADING";
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS";
export const TASK_CREATE_FAIL = "TASK_CREATE_FAIL";

export const TASK_UPDATE_LOADING = "TASK_UPDATE_LOADING";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_FAIL = "TASK_UPDATE_FAIL";

export const TASK_DELETE_LOADING = "TASK_DELETE_LOADING";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_FAIL = "TASK_DELETE_FAIL";

export const TASK_GET_LOADING = "TASK_GET_LOADING";
export const TASK_GET_SUCCESS = "TASK_GET_SUCCESS";
export const TASK_GET_FAIL = "TASK_GET_FAIL";

export const GET_USER_DATA_LOADING = "GET_USER_DATA_LOADING";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAIL = "GET_USER_DATA_FAIL";

export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const VERIFY_USER_LOADING = "VERIFY_USER_LOADING";
export const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
export const VERIFY_USER_FAIL = "VERIFY_USER_FAIL";

export const UN_VERIFY_USER_LOADING = "UN_VERIFY_USER_LOADING";
export const UN_VERIFY_USER_SUCCESS = "UN_VERIFY_USER_SUCCESS";
export const UN_VERIFY_USER_FAIL = "UN_VERIFY_USER_FAIL";

export const CREATE_BLOG_LOADING = "CREATE_BLOG_LOADING";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";

export const GET_IMAGE_LOADING = "GET_IMAGE_LOADING";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAIL = "GET_IMAGE_FAIL";

export const GET_BLOG_LOADING = "GET_BLOG_LOADING";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_FAIL = "GET_BLOG_FAIL";

export const UPLOAD_BLOG_LOADING = "UPLOAD_BLOG_LOADING";
export const UPLOAD_BLOG_SUCCESS = "UPLOAD_BLOG_SUCCESS";
export const UPLOAD_BLOG_FAIL = "UPLOAD_BLOG_FAIL";

export const CURRENT_USER_LOADING = "CURRENT_USER_LOADING";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";
export const CURRENT_USER_FAIL = "CURRENT_USER_FAIL";

export const MAKE_USER_ADMIN_LOADING = "MAKE_USER_ADMIN_LOADING";
export const MAKE_USER_ADMIN_SUCCESS = "MAKE_USER_ADMIN_SUCCESS";
export const MAKE_USER_ADMIN_FAIL = "MAKE_USER_ADMIN_FAIL";


export const REMOVE_USER_ADMIN_LOADING = "REMOVE_USER_ADMIN_LOADING";
export const REMOVE_USER_ADMIN_SUCCESS = "REMOVE_USER_ADMIN_SUCCESS";
export const REMOVE_USER_ADMIN_FAIL = "REMOVE_USER_ADMIN_FAIL";